### ISSUE TITLE
Where can I find `mica3/BIDS_MICs`?

### ISSUE THREAD

**Issue by JAQuent** [jordandekraker/hippomaps#31]
Hey, quick question: I would like to follow the task fMRI tutorial for **HippoMaps** but unfortunately I am unable to find the correct data that is referenced in the tutorial `/data/mica3/BIDS_MICs`. I see that it is also referenced in different places like here (https://github.com/MICA-MNI/z-brains) but I have not been able to find where one can download that data. Is that publicly available somewhere?

I am particularly interested in trying to map data to hippocampal surface because that's what I want to do with my own data but even when I try to have `useCheckpoints = True` I get the following error:

```
hm.fetcher.get_tutorialCheckpoints(['MRI-3T-taskfMRI_samplesubject-MST.npz'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alex/Desktop/HippUnfold_test/HippoMaps/hippomaps/hippomaps/fetcher.py", line 145, in get_tutorialCheckpoints
    h = name_hashes['/tutorialCheckpoints/' + fn]
KeyError: '/tutorialCheckpoints/MRI-3T-taskfMRI_samplesubject-MST.npz'

```

**Comment by jordandekraker** [comment]
Thanks for checking out our tutorials

`/data/mica3/BIDS_MICs` shows an example of where you might store your own neuroimaging data in BIDS format, but unfortunately we cannot share this data directly as it is very large. I include the code here to show how you might point these scripts to your own data. To replicate our experiments though, you can use our checkpoint system.

You're right that the file `'/tutorialCheckpoints/MRI-3T-taskfMRI_samplesubject-MST.npz'` was missing from our online repo! I'm uploading it now and it should be working shortly Let me know if you have any further issues!

**Comment by JAQuent** [comment]
Could be that `hm.fetcher.get_tutorialCheckpoints(['MRI-3T-taskfMRI_samplesubject-MST.npz'])` works now but `hm.fetcher.get_tutorialCheckpoints(['MRI-3T-taskfMRI_betas-MST.npz'])` still doesn't?

```
>>> if useCheckpoints:
...     hm.fetcher.get_tutorialCheckpoints(['MRI-3T-taskfMRI_samplesubject-MST.npz'])
...     hm.fetcher.get_tutorialCheckpoints(['MRI-3T-taskfMRI_betas-MST.npz'])
... 
100% [..........................................................................] 4100267 / 4100267Traceback (most recent call last):
  File "/usr/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/usr/lib/python3.10/http/client.py", line 1455, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/usr/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.10/ssl.py", line 1100, in _create
    self.do_handshake()
  File "/usr/lib/python3.10/ssl.py", line 1371, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/home/alex/Desktop/HippUnfold_test/HippoMaps/hippomaps/hippomaps/fetcher.py", line 146, in get_tutorialCheckpoints
    wget.download(f"https://files.ca-1.osf.io/v1/resources/{repoID}/providers/osfstorage{h}",out=checkpointsdir + fn)
  File "/home/alex/Desktop/HippUnfold_test/HippoMaps/venv/lib/python3.10/site-packages/wget.py", line 526, in download
    (tmpfile, headers) = ulib.urlretrieve(binurl, tmpfile, callback)
  File "/usr/lib/python3.10/urllib/request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)>
>>> hm.fetcher.get_tutorialCheckpoints(['MRI-3T-taskfMRI_samplesubject-MST.npz'])
>>> hm.fetcher.get_tutorialCheckpoints(['MRI-3T-taskfMRI_betas-MST.npz'])
Traceback (most recent call last):
  File "/usr/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/usr/lib/python3.10/http/client.py", line 1455, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/usr/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.10/ssl.py", line 1100, in _create
    self.do_handshake()
  File "/usr/lib/python3.10/ssl.py", line 1371, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alex/Desktop/HippUnfold_test/HippoMaps/hippomaps/hippomaps/fetcher.py", line 146, in get_tutorialCheckpoints
    wget.download(f"https://files.ca-1.osf.io/v1/resources/{repoID}/providers/osfstorage{h}",out=checkpointsdir + fn)
  File "/home/alex/Desktop/HippUnfold_test/HippoMaps/venv/lib/python3.10/site-packages/wget.py", line 526, in download
    (tmpfile, headers) = ulib.urlretrieve(binurl, tmpfile, callback)
  File "/usr/lib/python3.10/urllib/request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 557, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 749, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)>
```

**Comment by JAQuent** [comment]
Hey, I just had time to play around with `HippoMaps` again. I am very happy to report back that I can now download the tutorial data and I was generally able to run the tutorial code on my computer. Thank you so much. 👍 

Here are some things I had to do to make it work in case you're interested. None of the things were major to be honest.
1. I think the virtual environment code only works for Windows so I used `python3 -m venv myvenv` for running it on Ubuntu.
2. I didn't find documentation on `hm.fetcher.get_tutorialCheckpoints` and maybe it would be nice for this function to print the path where it saves the downloaded files. In my case it was the `HippoMaps` folder but not my current working directory. 
3. When running `hm.plotting.surfplot_canonical_foldunfold(contrasts_patternsep2, den='2mm', hemis=hemis, labels=labels, tighten_cwindow=True, unfoldAPrescale=True, cmap='bwr', color_range='sym', share='row', color_bar='right', embed_nb=True)` I got this error `ModuleNotFoundError: No module named 'IPython'`, which I fixed with `pip install IPython`.
